apiVersion: v1
kind: Secret

metadata:
  name: {{ include "python-redis.secretName" . }}
  labels:
    {{- include "python-redis.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: configuration

type: Opaque

stringData:
  REDIS_PASSWORD: {{ .Values.redis.secret.password | quote }}